### ISSUE TITLE
the diagram_helpdesk_ticket module does not install

### ISSUE THREAD

**Issue by gatecommerce** [Maralai/draw.io#2]
I noticed that the file "diagram_helpdesk_ticket/models/helpdesk_ticket.py.py" perhaps has the wrong name "...py.py";
in any case, even by correcting the name the module does not install correctly on odoo 17 enterprise rev.17.0+e.20240701

ImportError: cannot import name 'project_task' from partially initialized module 'odoo.addons.diagram_helpdesk_ticket.models' (most likely due to a circular import)

**Comment by Maralai** [comment]
Thanks @gatecommerce for posting this! 
I am not using `helpdesk` for my own purposes, and so it looks like I never finished that implementation. I have made the corrections, you can `git pull` to get the latest. For details on what changed see https://github.com/Maralai/odoo_diagram/commit/10e4f2eb8746a4946f7d30f6b732753bb88c1b60
